### ISSUE TITLE
FATAL: DB connection issue

### ISSUE THREAD

**Issue by 2000prath** [eneudys101/techcenter#22]
### Steps followed: 
1. Installed pip packages from requirements.txt
2. Create venv and activated
3. run command `docker-compose up` 
Database is started
`techcenter-postgres-database | 2022-03-30 07:07:23.620 UTC [27] LOG:  redo done at 0/16FBA50 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
techcenter-postgres-database | 2022-03-30 07:07:23.633 UTC [1] LOG:  database system is ready to accept connections`
5. Open another terminal, run `python manage.py migrate`
Got error:
` conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "techcenter"`

### Verification done:
* `docker-compose.yml` looks correct
`environment:
      POSTGRES_USER: techcenter
      POSTGRES_PASSWORD: techcenter
      POSTGRES_DB: techcenter`

* `settings.py` looks correct
`DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'techcenter',
        'USER': 'techcenter',
        'PASSWORD': 'techcenter',
        'HOST': 'localhost',
        'PORT': '5432',
    } 
}`

**Comment by eneudys101** [comment]
Thank you for trying to run the project. This is a very new project and it is not functional at all yet. Although it should be able to at least show the Django default test page.

As far as your issue. I was able to follow your steps on a new environment and was able to run the project. Make sure that you are not running another instance of a postgres database on the same port since you will not be connecting to the development database.

**Comment by 2000prath** [comment]
Ohh that correct, I had installed PostgreSQL on local and the port 5432 is consumed by PostgreSQL DB. 
Fix: I changed the port number in `docker-compose.yml`, Now its working!

Closing the ticket..! Thanks!
